[phases.setup]
nixPkgs = ["python312", "xorg.libxcb", "xorg.libX11", "xorg.libXext", "xorg.libXrender", "xorg.libXtst", "libGL"]

[phases.install]
cmds = ["python3 -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = [". /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "gunicorn wsgi:app"